/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CrearEventoRouteImport } from './routes/crear-evento'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventoIdRouteImport } from './routes/evento/$id'

const CrearEventoRoute = CrearEventoRouteImport.update({
  id: '/crear-evento',
  path: '/crear-evento',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventoIdRoute = EventoIdRouteImport.update({
  id: '/evento/$id',
  path: '/evento/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crear-evento': typeof CrearEventoRoute
  '/evento/$id': typeof EventoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crear-evento': typeof CrearEventoRoute
  '/evento/$id': typeof EventoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/crear-evento': typeof CrearEventoRoute
  '/evento/$id': typeof EventoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/crear-evento' | '/evento/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/crear-evento' | '/evento/$id'
  id: '__root__' | '/' | '/about' | '/crear-evento' | '/evento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CrearEventoRoute: typeof CrearEventoRoute
  EventoIdRoute: typeof EventoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/crear-evento': {
      id: '/crear-evento'
      path: '/crear-evento'
      fullPath: '/crear-evento'
      preLoaderRoute: typeof CrearEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evento/$id': {
      id: '/evento/$id'
      path: '/evento/$id'
      fullPath: '/evento/$id'
      preLoaderRoute: typeof EventoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CrearEventoRoute: CrearEventoRoute,
  EventoIdRoute: EventoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
